# A set of sample requests covering raising product updates for part #6

@CatalogService_Web_HostAddress = http://localhost:5164

# Create a category

POST {{CatalogService_Web_HostAddress}}/api/categories
Content-Type: application/json

{
    "name": "Good products"
}

###

# Create products

POST {{CatalogService_Web_HostAddress}}/api/products
Content-Type: application/json

{
    "name": "Sample Product 1",
    "categoryId": 1,
    "price": 500,
    "amount": 1000,
    "description": "A basic product #1"
}

###

POST {{CatalogService_Web_HostAddress}}/api/products
Content-Type: application/json

{
    "name": "Sample Product 2",
    "categoryId": 1,
    "price": 500,
    "amount": 1000,
    "description": "A basic product #2"
}

###

POST {{CatalogService_Web_HostAddress}}/api/products
Content-Type: application/json

{
    "name": "Sample Product 3",
    "categoryId": 1,
    "price": 500,
    "amount": 1000,
    "description": "A basic product #3"
}

###

# Make sure that the same products are added to Cart service

GET {{CatalogService_Web_HostAddress}}/api/products
Content-Type: application/json

###

# Update products

PUT {{CatalogService_Web_HostAddress}}/api/products/1
Content-Type: application/json

{
    "name": "Sample Product 1 - Updated",
    "id": 1,
    "categoryId": 1,
    "price": 199,
    "amount": 10,
    "description": "A basic product #1 - Updated"
}

###

PUT {{CatalogService_Web_HostAddress}}/api/products/2
Content-Type: application/json

{
    "name": "Sample Product 2 - Updated",
    "id": 2,
    "categoryId": 1,
    "price": 199,
    "amount": 10,
    "description": "A basic product #2 - Updated"
}

###

PUT {{CatalogService_Web_HostAddress}}/api/products/3
Content-Type: application/json

{
    "name": "Sample Product 3 - Updated",
    "id": 3,
    "categoryId": 1,
    "price": 199,
    "amount": 10,
    "description": "A basic product #3 - Updated"
}