services:
  eshop-message-broker:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: eshopuser
      RABBITMQ_DEFAULT_PASS: sKxX8nYq97FX

  eshop-identity-server:
    image: ${DOCKER_REGISTRY-}eshop-identity-server
    build:
      context: .
      dockerfile: Dependencies/identity-server/Dockerfile
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

  cartservice:
    image: ${DOCKER_REGISTRY-}cartservice
    environment:
      ESHOP_MessageBrokerConfig__UserName: eshopuser
      ESHOP_MessageBrokerConfig__Password: sKxX8nYq97FX
      ESHOP_MessageBrokerConfig__HostName: eshop-message-broker
      ESHOP_MessageBrokerConfig__VirtualHost: "/"
      ESHOP_MessageBrokerConfig__Port: 5672
      ESHOP_JwtTokenConfig__Authority: "http://eshop-identity-server:8080/realms/eshop-identity"
      ESHOP_JwtTokenConfig__Issuer: "eshop-client"
      ESHOP_ConnectionStrings__DefaultConnection: "mongodb://admin:3f8nLnAez30z@cartservice-db:27017"
      ESHOP_DataSourceConfig__DbName: eshop-cart
      ESHOP_DataSourceConfig__CartCollectionName: carts
      ESHOP_DataSourceConfig__ProductCollectionName: products
    build:
      context: .
      dockerfile: CartService/Dockerfile
    depends_on:
      - eshop-message-broker
      - cartservice-db
    ports:
      - "5010:8080"
  
  cartservice-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 3f8nLnAez30z
    volumes:
      - cartservice-data:/data/db
 
  catalogservice.web:
    image: ${DOCKER_REGISTRY-}catalogserviceweb
    environment:
      ESHOP_MessageBrokerConfig__UserName: eshopuser
      ESHOP_MessageBrokerConfig__Password: sKxX8nYq97FX
      ESHOP_MessageBrokerConfig__HostName: eshop-message-broker
      ESHOP_MessageBrokerConfig__VirtualHost: "/"
      ESHOP_MessageBrokerConfig__Port: 5672
      ESHOP_JwtTokenConfig__Authority: "http://eshop-identity-server:8080/realms/eshop-identity"
      ESHOP_JwtTokenConfig__Issuer: "eshop-client"
      ESHOP_ConnectionStrings__DefaultConnection: Server=catalogservice-db,1433;Database=catalog-db;User Id=sa;Password=04PN849Q23Xh;Encrypt=False
    build:
      context: .
      dockerfile: CatalogService/CatalogService.Web/Dockerfile
    depends_on:
      - eshop-message-broker
      - catalogservice-db
    ports:
      - "5020:8080"

  catalogservice-db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "04PN849Q23Xh"
      ACCEPT_EULA: "Y"
    volumes:
      - calatalogservice-data:/var/opt/mssql

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    environment:
      ESHOP_JwtTokenConfig__Authority: "http://eshop-identity-server:8080/realms/eshop-identity"
      ESHOP_JwtTokenConfig__Issuer: "eshop-client"
    ports:
      - "5000:8080"
      - "5001:8081"

volumes:
  calatalogservice-data:
    driver: local
  cartservice-data:
    driver: local
