services:
  eshop-message-broker:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: eshopuser
      RABBITMQ_DEFAULT_PASS: sKxX8nYq97FX
    ports:
      - "15672:15672"
      - "5672:5672"

  eshop-identity-server:
    image: ${DOCKER_REGISTRY-}eshop-identity-server
    build:
      context: .
      dockerfile: Dependencies/identity-server/Dockerfile
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "5177:8080"

  cartservice:
    image: ${DOCKER_REGISTRY-}cartservice
    environment:
      ESHOP_MessageBrokerConfig__UserName: eshopuser
      ESHOP_MessageBrokerConfig__Password: sKxX8nYq97FX
      ESHOP_MessageBrokerConfig__HostName: eshop-message-broker
      ESHOP_MessageBrokerConfig__VirtualHost: "/"
      ESHOP_MessageBrokerConfig__Port: 5672
      ESHOP_JwtTokenConfig__Authority: "http://eshop-identity-server:8080/realms/eshop-identity"
      ESHOP_JwtTokenConfig__Issuer: "eshop-client"
      ESHOP_ConnectionStrings__DefaultConnection: "mongodb://admin:admin@cartservice-db:27017"
      ESHOP_DataSourceConfig__DbName: eshop-cart
      ESHOP_DataSourceConfig__CartCollectionName: carts
      ESHOP_DataSourceConfig__ProductCollectionName: products
    build:
      context: .
      dockerfile: CartService/Dockerfile
    depends_on:
      - eshop-message-broker
    ports:
      - "5136:8080"
      - "5137:8081"
  
  cartservice-db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - cartservice-data:/data/db
 
  catalogservice.web:
    image: ${DOCKER_REGISTRY-}catalogserviceweb
    environment:
      ESHOP_MessageBrokerConfig__UserName: eshopuser
      ESHOP_MessageBrokerConfig__Password: sKxX8nYq97FX
      ESHOP_MessageBrokerConfig__HostName: eshop-message-broker
      ESHOP_MessageBrokerConfig__VirtualHost: "/"
      ESHOP_MessageBrokerConfig__Port: 5672
      ESHOP_JwtTokenConfig__Authority: "http://eshop-identity-server:8080/realms/eshop-identity"
      ESHOP_JwtTokenConfig__Issuer: "eshop-client"
      ESHOP_ConnectionStrings__DefaultConnection: Data source=CatalogDb.db
    build:
      context: .
      dockerfile: CatalogService/CatalogService.Web/Dockerfile
    ports:
      - "5164:8080"
      - "5165:8081"

volumes:
  calatalog-service-data:
  cartservice-data:
    driver: local
